# ---- build stage ----
FROM gradle:8.10.2-jdk21-alpine AS build
WORKDIR /app

# 1) копируем только файлы сборки для кеша зависимостей
COPY settings.gradle build.gradle gradle.properties* ./
COPY gradle ./gradle
# прогреваем зависимости (без исходников) — лёгкая задача, кэшируется отлично
RUN gradle --no-daemon dependencies || true

# 2) теперь копируем весь проект и собираем jar
COPY . .
RUN gradle clean bootJar --no-daemon

# ---- runtime stage ----
FROM eclipse-temurin:21-jre-alpine
ENV JAVA_TOOL_OPTIONS="-XX:+UseZGC -Xms256m -Xmx512m"
ENV SPRING_PROFILES_ACTIVE=prod
WORKDIR /app
# копируем единственный fat-jar
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
USER 1000:1000
ENTRYPOINT ["java","-jar","/app/app.jar"]
