# ---- build stage ----
FROM node:20-alpine AS build
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# ---- runtime stage ----
FROM nginx:stable-alpine
# минимальный конфиг для SPA/статик
COPY nginx.prod.conf /etc/nginx/nginx.conf
COPY --from=build /app/frontend/dist/ /usr/share/nginx/html/
EXPOSE 80
