apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: open-marketplace
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://postgresql:5432/open_market_placer
  DB_USER: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: change-me-please-32chars-min
